### ISSUE TITLE
Using scipy's genetic algorithm for fitting Raman spectroscopy data 

### ISSUE THREAD

**Issue by zunzun** [EdoardoPona/Genetic-Algorithms#1]
I see from your GitHub project that you are starting to work with genetic algorithms in Python. The authors of scipy have added a genetic algorithm for initial parameter estimation in curve fitting, the module is named scipy.optimize.differential_evolution.

I have used scipy's Differential Evolution genetic algorithm to determine initial parameters for fitting a double Lorentzian peak equation to Raman spectroscopy data and found that the results were excellent. The GitHub project, with a test spectroscopy data file, is:

https://github.com/zunzun/RamanSpectroscopyFit

If you have any questions, please let me know. My background is in nuclear engineering and industrial radiation physics, and I love Python so I will be glad to help.

James Phillips

**Comment by EdoardoPona** [comment]
Hello, thanks for letting me know about the new module in scipy, I had missed that! I'll be experimenting with it, and maybe in the future I'll use it in some project, although at the moment I am trying to figure out how to evolve virtual creatures controlled by neural networks.
The project you posted is really cool!
